name: Publish canary
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish-canary:
    runs-on: "ubuntu-latest"
    name: Publish canary release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"
          scope: "@mnikesh"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - run: echo "${{github.head_ref}} --- ${{github.sha}}"
      - run: |
          cat ${{github.workspace}}/.npmrc
      - name: Lerna publish canary
        run: |
          npm run lerna publish -- \
            --yes \
            --canary \
            --preid ${{github.head_ref}} \
            --dist-tag ${{github.sha}} \
            --summary-file
      - run: ls -al
      - name: Post canary release comment
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require("fs");
            let commentBody = 'No packages were published.';
            try {
              const summary = fs.readFileSync("./lerna-publish-summary.json");
              const summaryJson = JSON.parse(summary);
              commentBody = "The following packages were published:\n\n";
              commentBody += summaryJson.map(item => `- ${item.packageName} (${item.version})`).join("\n");
            } catch (err) {
              console.error("Error reading summary file:", err);
            }

            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            } catch(err) {
              console.error("Error parsing summary file:", err);
            }
